version: '3.7'
services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 'my-root-password'
      MYSQL_DATABASE: 'bookstore_db'
      MYSQL_USER: 'clarusway'
      MYSQL_PASSWORD: 'clarusway_1'
    networks:
      - clarusnet
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s 
      timeout: 10s
      retries: 5

  myapp:
    image: abraham/bookstoreapi:latest
    container_name: myapp
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - clarusnet

networks:
  clarusnet:
    driver: bridge
