apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: {{ .Values.webserver_image }}
        name: project03-webserver
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: mysql-secret
        - configMapRef:
            name: servers-configmap
        resources:
          requests: 
            memory: "200Mi"
            cpu:  "100m"
          limits:
            memory: "750Mi"
            cpu:  "750m"