apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

# Volume hosting is done by workerNode,
# HostPath will look for /mnt/data once all run!
# will mount if there is, if not will create it and mount!
