apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

# Tough Pvc is #Gi as ther is 
# only one Pv of 5 Gi
# then pv will be of 5Gi vol!