- name: Docker install and configuration
  hosts: _development
  become: true
  roles: 
    - docker #path to file registered in ansible.cfg file.
    # - geerlingguy.docker #from ansible-galaxy install.

- name: Postgre Database configuration
  hosts: _ansible_postgresql
  become: true
  roles:
    - postgre

- name: Nodejs server configuration
  hosts: _ansible_nodejs
  become: true
  roles:
    - nodejs

- name: React UI Server configuration
  hosts: _ansible_react
  become: true
  roles:
    - react


#path to file registered in ansible.cfg file.
#vars are seperately recorded in related var files.