apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UjEyMzRy
  MYSQL_PASSWORD: Q2xhcmlzd2F5XzE=
 


#! The passwords Clarusway_1 and R1234r should be encoded first. 
#For this, use:
# echo -n 'R1234r' | base64   ---> Addressed as mysql-root-password in the mysql-secret.yaml file
# echo -n 'Clarusway_1' | base64 ----> Addressed as mysql-admin-password in the mysql-secret.yaml file

# To decode the passwords Clarusway_1 and R1234r:
# echo -n 'UjEyMzRy' | base64 --decode     ---> It gives us the root password
# echo -n 'Q2xhcnVzd2F5XzE=' | base64 --decode   ---> It gives us the admin password




# - containerPort: 3306
# env:
#   - name: MYSQL_ROOT_PASSWORD
#     valueFrom:
#       secretKeyRef:
#         name: mysql-secret
#         key: mysql-root-password
#   - name: MYSQL_PASSWORD
#     valueFrom:
#       secretKeyRef:
#         name: mysql-secret
#         key: mysql-password
#   - name: MYSQL_USER
#     value: clarus
#   - name: MYSQL_DATABASE
#     value: phonebook
# resources: {}

# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-secret
# type: Opaque
# data:
#   mysql-root-password: UjEyMzRy
#   mysql-password: Q2xhcmlzd2F5XzE=

